baseURL = ""
languageCode = "it-it"
title = ""

[params]
    author = ""

    [params.podcast]
        title = "Hugo Podcast"
        subtitle = "Subtitle"
        summary = "Summary"
        authors = [ "Author" ]
        email = "example@example.com"
        image = "/img/podcast-logo.png"
        audio_base_url = "https://cdn.example.com/podcast/"
        copyright = "Copyright"
        category = "Category"
        sub_category = "Sub Category"
        explicit = "no"
        iTunesID = 12345677
        update_period = "weekly"
        update_frequency = 1
        funding_url = "https://example.com/funding"
        funding_text = "Buy me a coffee"

[taxonomies]
    podcast_tags = "podcast_tag"
