baseURL = ""
languageCode = "it-it"
title = ""

[params]
    author = ""

    [params.podcast]
        title = ""
        subtitle = ""
        summary = ""
        email = "example@example.com"
        image = "/img/podcast-logo.png"
        audio_base_url = ''
        copyright = ""
        category = ""
        sub_category = ""
        explicit = "no"
        iTunesID = 12345677
        funding_url = ""
        funding_text = ""

[taxonomies]
    podcast_tags = "podcast_tag"
